baseURL = "https://reitzig.github.io/today-i-learned/"
title = "Today I Learned"
languageCode = "en-us"
copyright = """
    Â© 2020 Raphael Reitzig
    <br />
    This work is licensed under a 
    <a rel='license' href='http://creativecommons.org/licenses/by/4.0/'>
        Creative Commons Attribution 4.0 International License
    </a>.
    <br />
    <a rel='license' href='http://creativecommons.org/licenses/by/4.0/'>
        <img alt='Creative Commons License' style='border-width:0' src='cc-by-80x15.png' />
    </a>
"""

theme = "hugo-notepadium"

[params]
author = "Raphael Reitzig"
#slogan = "Lesson of the day"
license = ""

[params.nav]
showTags = true             # /tags/

#[[params.nav.custom]]
#title = "Github"
#url = "https://github.com/reitzig"

[[params.nav.custom]]
title = "About"
url = "impressum"

[params.syntax]
use = "hljs"
theme = "github"

[params.assets]
css = [
    "css/fixes.css", 
    "css/admonitions.css",
    "css/privacy_hacks.css" # TODO: only in impressum.adoc ?
]
